# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(130, 10, 151, 21))
        self.titleLabel.setObjectName("titleLabel")
        self.labelPlain = QtWidgets.QLabel(self.centralwidget)
        self.labelPlain.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.labelPlain.setObjectName("labelPlain")
        self.plainText = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText.setGeometry(QtCore.QRect(100, 50, 250, 22))
        self.plainText.setObjectName("plainText")
        self.labelKey = QtWidgets.QLabel(self.centralwidget)
        self.labelKey.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.labelKey.setObjectName("labelKey")
        self.keyInput = QtWidgets.QLineEdit(self.centralwidget)
        self.keyInput.setGeometry(QtCore.QRect(100, 90, 250, 22))
        self.keyInput.setObjectName("keyInput")
        self.labelCipher = QtWidgets.QLabel(self.centralwidget)
        self.labelCipher.setGeometry(QtCore.QRect(20, 130, 71, 21))
        self.labelCipher.setObjectName("labelCipher")
        self.cipherText = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText.setGeometry(QtCore.QRect(100, 130, 250, 22))
        self.cipherText.setObjectName("cipherText")
        self.encryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptBtn.setGeometry(QtCore.QRect(100, 180, 93, 28))
        self.encryptBtn.setObjectName("encryptBtn")
        self.decryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptBtn.setGeometry(QtCore.QRect(260, 180, 93, 28))
        self.decryptBtn.setObjectName("decryptBtn")
        Ui_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ui_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle(_translate("Ui_MainWindow", "Caesar Cipher"))
        self.titleLabel.setText(_translate("Ui_MainWindow", "CAESAR CIPHER"))
        self.labelPlain.setText(_translate("Ui_MainWindow", "Plain Text"))
        self.labelKey.setText(_translate("Ui_MainWindow", "Key"))
        self.labelCipher.setText(_translate("Ui_MainWindow", "Cipher Text"))
        self.encryptBtn.setText(_translate("Ui_MainWindow", "Encrypt"))
        self.decryptBtn.setText(_translate("Ui_MainWindow", "Decrypt"))
